Allow unprivileged user to run VTN Coordinator.
  * A user who runs VTN Coordinator needs to have write permission
    for /usr/local/vtn/var directory.
  * db_setup command installs ownership of VTN Coordinator.
    Only a user who executed db_setup command can execute VTN commands,
    vtn_start, vtn_stop, and db_setup.
  * "db_setup -c" reset VTN Coordinator environment to initial state.
    * All data and log files are erased.

Change-Id: I366c14559bafe6bd0284815824bac7871721040b
Signed-off-by: Shigeru Yasuda <s-yasuda@da.jp.nec.com>

diff --git a/coordinator/cmds/dbm/db_control/db_start.in b/coordinator/cmds/dbm/db_control/db_start.in
--- a/coordinator/cmds/dbm/db_control/db_start.in
+++ b/coordinator/cmds/dbm/db_control/db_start.in
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (c) 2012-2013 NEC Corporation
+# Copyright (c) 2012-2014 NEC Corporation
 # All rights reserved.
 # 
 # This program and the accompanying materials are made available under the
@@ -15,6 +15,16 @@
 
 dbmf=%INST_SYSSCRIPTDIR%/dbm/dbm_functions
 [ -r $dbmf ] || { echo "dbm_functions not found"; exit 2; } && . $dbmf
+
+VTN_FUNCS=%INST_DATADIR%/vtn_funcs.sh
+
+. $VTN_FUNCS
+if [ $? -ne 0 ]; then
+    echo "*** ERROR: Failed to import common configuration." >&2
+    exit 1
+fi
+
+init_env
 
 # single_db_start()
 # 
@@ -40,45 +50,7 @@ single_db_start()
 	return $status
 }
 
-# odbc_dsn_install()
-# 
-#	ODBC system DSN is installed.
-#
-# * input
-#	   Nothing
-#
-# * output
-#	   0: Success
-#	   2: Failure
-#
-odbc_dsn_install()
-{
-	if [ ! -r $ODBCINSTALLEDFILE ]; then
-		/usr/bin/odbcinst -i -s -l -f $ODBCINIFILE > $TMPLOGFILE
-		if [ $? -ne 0 ]; then
-			error_output odbc $DBLOGFILE $TMPLOGFILE
-			db_stop 2> $TMPLOGFILE
-			if [ $? -ne 0 ]; then
-				error_output dbstop $DBLOGFILE $TMPLOGFILE
-			fi
-			return 2
-		fi
-		rm -f $TMPLOGFILE
-		su -m $SUUSER -c "touch $ODBCINSTALLEDFILE" 2> $TMPLOGFILE
-		if [ $? -ne 0 ]; then
-			error_output copy $DBLOGFILE $TMPLOGFILE
-			db_stop 2> $TMPLOGFILE
-			if [ $? -ne 0 ]; then
-				error_output dbstop $DBLOGFILE $TMPLOGFILE
-			fi
-			return 2
-		fi
-	fi
-	return 0
-}
-
-check_user_permission || exit 2
-[ $# -ge 2 ] && { echo "*** Error: Invalid argument."; exit 2; }
+[ $# -ge 2 ] && { echo "*** ERROR: Invalid argument."; exit 2; }
 
 export_pg_env
 
@@ -87,9 +59,6 @@ TMPLOGFILE=$DBMTMPDIR/unc_start_db_$$.log
 trap 'rm -f $TMPLOGFILE; trap_rm_tmpfile unc_start_db' 0
 
 single_db_start
-status=$?
-[ $status -ne 0 ] && exit $status
-odbc_dsn_install
 status=$?
 [ $status -ne 0 ] && exit $status
 
diff --git a/coordinator/cmds/dbm/db_control/db_stop.in b/coordinator/cmds/dbm/db_control/db_stop.in
--- a/coordinator/cmds/dbm/db_control/db_stop.in
+++ b/coordinator/cmds/dbm/db_control/db_stop.in
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #
-# Copyright (c) 2012-2013 NEC Corporation
+# Copyright (c) 2012-2014 NEC Corporation
 # All rights reserved.
 # 
 # This program and the accompanying materials are made available under the
@@ -16,8 +16,17 @@
 dbmf=%INST_SYSSCRIPTDIR%/dbm/dbm_functions
 [ -r $dbmf ] || { echo "dbm_functions not found"; exit 1; } && . $dbmf
 
-check_user_permission || exit 1
-[ $# -ne 0 ] && { echo "*** Error: Invalid argument."; exit 1; }
+VTN_FUNCS=%INST_DATADIR%/vtn_funcs.sh
+
+. $VTN_FUNCS
+if [ $? -ne 0 ]; then
+    echo "*** ERROR: Failed to import common configuration." >&2
+    exit 1
+fi
+
+init_env
+
+[ $# -ne 0 ] && { echo "*** ERROR: Invalid argument."; exit 1; }
 
 export_pg_env
 
diff --git a/coordinator/scripts/vtn_start.in b/coordinator/scripts/vtn_start.in
--- a/coordinator/scripts/vtn_start.in
+++ b/coordinator/scripts/vtn_start.in
@@ -1,7 +1,7 @@
 #!%SHELL_PATH%
 
 #
-# Copyright (c) 2012-2013 NEC Corporation
+# Copyright (c) 2012-2014 NEC Corporation
 # All rights reserved.
 # 
 # This program and the accompanying materials are made available under the
@@ -19,23 +19,57 @@ PATH=%PATH_SCRIPT%
 export PATH
 umask 022
 
-DB_START=%INST_SBINDIR%/db_start
-UNCD_START=%INST_SBINDIR%/uncd_start
 UNC_DMCTL=%INST_BINDIR%/unc_dmctl
+VTN_FUNCS=%INST_DATADIR%/vtn_funcs.sh
+
+. $VTN_FUNCS
+if [ $? -ne 0 ]; then
+    echo "*** ERROR: Failed to import common configuration." >&2
+    exit 1
+fi
+
+init_env
+
+if [ -f $DOT_RUNNING ]; then
+    echo "*** ERROR: VTN is running." >&2
+    exit 1
+fi
+
+status=1
+
+fatal_error()
+{
+    if [ -n "$RUN_UNCD" ]; then
+        $UNCD_STOP  
+    fi
+    if [ -n "$RUN_DB" ]; then
+        $DB_STOP
+    fi
+
+    echo "*** ERROR: $1" >&2
+
+    exit $status
+}
 
 # Start database
 $DB_START
 status=$?
-if [ $status -ne 0 ]; then
-    exit $status
-fi
+[ $status -ne 0 ] && fatal_error "Failed to start database."
+RUN_DB=1
 
 # Start the UNC daemon.
 $UNCD_START
 status=$?
-if [ $status -ne 0 ]; then
-    exit $status
-fi
+[ $status -ne 0 ] && fatal_error "Failed to start the UNC daemon."
+RUN_UNCD=1
 
 # Activate the UNC daemon.
 $UNC_DMCTL clevent ACT
+status=$?
+[ $status -ne 0 ] && fatal_error "Failed to activate the UNC daemon."
+
+touch $DOT_RUNNING 
+status=$?
+[ $status -ne 0 ] && fatal_error "Failed to write state file."
+
+exit 0
diff --git a/coordinator/scripts/vtn_stop.in b/coordinator/scripts/vtn_stop.in
--- a/coordinator/scripts/vtn_stop.in
+++ b/coordinator/scripts/vtn_stop.in
@@ -1,7 +1,7 @@
 #!%SHELL_PATH%
 
 #
-# Copyright (c) 2012-2013 NEC Corporation
+# Copyright (c) 2012-2014 NEC Corporation
 # All rights reserved.
 # 
 # This program and the accompanying materials are made available under the
@@ -10,7 +10,7 @@
 #
 
 ##
-## Start the VTN
+## Stop the VTN
 ##
 
 IFS="
@@ -19,11 +19,27 @@ PATH=%PATH_SCRIPT%
 export PATH
 umask 022
 
-DB_STOP=%INST_SBINDIR%/db_stop
-UNCD_STOP=%INST_SBINDIR%/uncd_stop
+VTN_FUNCS=%INST_DATADIR%/vtn_funcs.sh
+
+. $VTN_FUNCS
+if [ $? -ne 0 ]; then
+    echo "*** ERROR: Failed to import common configuration." >&2
+    exit 1
+fi
+
+init_env
 
 # Terminate the UNC daemon.
 $UNCD_STOP
 
 # Terminate database
 $DB_STOP
+
+rm -f $DOT_RUNNING
+status=$?
+if [ $status -ne 0 ]; then
+    echo "*** ERROR: Failed to remove state file."
+    exit $status
+fi
+
+exit 0
