Bug 1177: Change "unix_socket_directory" paramter for PostgreSQL 9.3.
"unix_socket_directory" parameter in postgresql.conf was renamed to
"unix_socket_directories" in PostgreSQL 9.3. This patch makes db_setup
script define "unix_socket_directories" parameter to specify UNIX socket
directory when it detects PostgreSQL 9.3 or later.

Change-Id: I3dda6064eaadfc24baee87da12ab0ef8675c78f6
Signed-off-by: Shigeru Yasuda <s-yasuda@da.jp.nec.com>

diff --git a/coordinator/cmds/dbm/common/dbm_functions.in b/coordinator/cmds/dbm/common/dbm_functions.in
--- a/coordinator/cmds/dbm/common/dbm_functions.in
+++ b/coordinator/cmds/dbm/common/dbm_functions.in
@@ -444,16 +444,40 @@ copy_postgresql_file()
 #	copy postgresql.conf
 #
 # * input
-#	   Nothing
+#      arg1: PostgreSQL major version number
+#      arg2: PostgreSQL minor version number
 #
 # * output
-#	   0: Success
-#	   1: Failure
+#      0: Success
+#      1: Failure
 #
 copy_postgresql_conf()
 {
+	local major=$1
+	local minor=$2
+
+	# Determine parameter that specifies UNIX domain socket path.
+	local uds
+	if [ "$major" -gt 9 -o \( "$major" -eq 9 -a "$minor" -ge 3 \) ]; then
+		uds="unix_socket_directories"
+	else
+		uds="unix_socket_directory"
+	fi
+
+	# Update postgresql.conf.
+	local tmp="${POSTFILE}_tmp.$$"
+	sed -e "s,%unix_socket_directory%,$uds," $SINGLEPOSTFILE > $tmp
+	if [ $? -ne 0 ]; then
+		rm -f $tmp
+		return 1
+	fi
+
 	# Install postgresql.conf.
-	copy_postgresql_file $SINGLEPOSTFILE $POSTFILE || return 1
+	copy_postgresql_file $tmp $POSTFILE
+	local status=$?
+	rm -f $tmp
+
+	return $status
 }
 
 # create_setting_file()
